import type { Place } from "@/lib/types";

export const MOCK_PLACES: Place[] = [
  {
    id: "ua-embassy",
    name: "Посольство України в Чехії",
    category: "legal",
    address: "Charlese de Gaulle 29, Praha 6",
    lat: 50.1038,
    lng: 14.3946,
    phone: "+420 233 342 000",
    website: "https://czechia.mfa.gov.ua",
    hours: { today: "09:00-12:00" },
    languages: ["uk", "cs"],
    tags: ["документи", "консульство", "офіційно"],
    photos: [],
    is_verified: true,
    is_active: true,
    is_free: true,
    views_count: 1254,
    saves_count: 318,
    rating: 4.8,
    review_count: 40,
    distance_label: "4.2 км",
    city: "Praha",
    google_maps_url: "https://maps.google.com/?q=50.1038,14.3946",
    description:
      "Консульські послуги, документи та офіційна інформація для громадян України в Чехії.",
  },
  {
    id: "icp-praha",
    name: "Integrační centrum Praha",
    category: "legal",
    address: "Žitná 1574/51, Praha 1",
    lat: 50.0773,
    lng: 14.4262,
    phone: "+420 252 543 846",
    website: "https://icpraha.com",
    hours: { today: "09:00-17:00" },
    languages: ["uk", "cs", "en"],
    tags: ["інтеграція", "консультації", "курси"],
    photos: [],
    is_verified: true,
    is_active: true,
    is_free: true,
    views_count: 1088,
    saves_count: 246,
    rating: 4.7,
    review_count: 36,
    distance_label: "1.1 км",
    city: "Praha",
    description:
      "Міський центр інтеграції з консультаціями, курсами чеської та підтримкою для іноземців у Празі.",
  },
  {
    id: "cic-praha",
    name: "Centrum pro integraci cizinců",
    category: "legal",
    address: "Pernerova 32/10, Praha 8",
    lat: 50.0908,
    lng: 14.4499,
    phone: "+420 704 600 700",
    website: "https://www.cicops.cz",
    hours: { today: "10:00-17:00" },
    languages: ["uk", "cs", "en"],
    tags: ["інтеграція", "соціальна допомога", "право"],
    photos: [],
    is_verified: true,
    is_active: true,
    is_free: true,
    views_count: 943,
    saves_count: 221,
    rating: 4.7,
    review_count: 28,
    distance_label: "2.1 км",
    city: "Praha",
    description:
      "Консультації для іноземців щодо життя в Чехії, документів, роботи та адаптації.",
  },
  {
    id: "inbaze",
    name: "InBáze",
    category: "community",
    address: "Legerova 357/50, Praha 2",
    lat: 50.0724,
    lng: 14.4292,
    phone: "+420 739 037 353",
    website: "https://inbaze.cz",
    hours: { today: "09:00-17:00" },
    languages: ["uk", "cs", "en"],
    tags: ["спільнота", "родини", "інтеграція"],
    photos: [],
    is_verified: true,
    is_active: true,
    is_free: true,
    views_count: 704,
    saves_count: 190,
    rating: 4.8,
    review_count: 24,
    distance_label: "1.4 км",
    city: "Praha",
    description:
      "Громадська організація з програмами для мігрантів, сімей, дітей і локальних спільнот.",
  },
  {
    id: "mlp-central-library",
    name: "Міська бібліотека Праги",
    category: "language",
    address: "Mariánské náměstí 1, Praha 1",
    lat: 50.0871,
    lng: 14.4176,
    phone: "+420 222 113 555",
    website: "https://www.mlp.cz",
    hours: { today: "09:00-20:00" },
    languages: ["cs", "en"],
    tags: ["чеська", "книги", "події"],
    photos: [],
    is_verified: true,
    is_active: true,
    is_free: true,
    views_count: 632,
    saves_count: 141,
    rating: 4.9,
    review_count: 58,
    distance_label: "0.8 км",
    city: "Praha",
    description:
      "Центральна бібліотека з мовними матеріалами, подіями та простором для навчання в центрі Праги.",
  },
  {
    id: "nova-skola",
    name: "Nová škola",
    category: "language",
    address: "Křižíkova 344/6, Praha 8",
    lat: 50.091,
    lng: 14.4398,
    phone: "+420 222 540 029",
    website: "https://novaskolaops.cz",
    hours: { today: "09:00-17:00" },
    languages: ["uk", "cs"],
    tags: ["освіта", "діти", "чеська"],
    photos: [],
    is_verified: true,
    is_active: true,
    is_free: false,
    views_count: 732,
    saves_count: 147,
    rating: 4.8,
    review_count: 19,
    distance_label: "1.9 км",
    city: "Praha",
    description:
      "Освітня організація з програмами підтримки дітей, шкіл і родин з міграційним досвідом.",
  },
  {
    id: "urad-prace-praha",
    name: "Úřad práce Praha",
    category: "work",
    address: "Domažlická 1139/11, Praha 3",
    lat: 50.0872,
    lng: 14.4667,
    phone: "+420 950 178 111",
    website: "https://www.uradprace.cz",
    hours: { today: "08:00-17:00" },
    languages: ["cs"],
    tags: ["робота", "вакансії", "допомога"],
    photos: [],
    is_verified: true,
    is_active: true,
    is_free: true,
    views_count: 856,
    saves_count: 202,
    rating: 4.1,
    review_count: 25,
    distance_label: "3.0 км",
    city: "Praha",
    description:
      "Офіційна служба зайнятості: вакансії, реєстрація, допомога з працевлаштуванням і консультації.",
  },
  {
    id: "charita-praha",
    name: "Arcidiecézní charita Praha",
    category: "community",
    address: "Londýnská 44, Praha 2",
    lat: 50.0743,
    lng: 14.4346,
    phone: "+420 224 246 519",
    website: "https://praha.charita.cz",
    hours: { today: "09:00-16:00" },
    languages: ["uk", "cs"],
    tags: ["допомога", "родини", "гуманітарно"],
    photos: [],
    is_verified: true,
    is_active: true,
    is_free: true,
    views_count: 812,
    saves_count: 267,
    rating: 4.7,
    review_count: 33,
    distance_label: "1.6 км",
    city: "Praha",
    description:
      "Гуманітарна й соціальна підтримка, консультації та допомога людям у складних життєвих ситуаціях.",
  },
  {
    id: "slovo-prague",
    name: "SLOVO",
    category: "cafe",
    address: "Čermákova 1231/4, Praha",
    lat: 50.071263269088995,
    lng: 14.441634315342668,
    phone: "+420 721 877 871",
    website: "https://www.instagram.com/slovo_prague/",
    hours: { today: "Уточнюється" },
    languages: ["uk", "cs"],
    tags: ["кондитерська", "українська кухня", "сучасне"],
    photos: ["https://www.uagastromapa.cz/img/restaurants/slovo.png"],
    is_verified: true,
    is_active: true,
    is_free: false,
    views_count: 911,
    saves_count: 202,
    rating: 4.8,
    review_count: 31,
    distance_label: "1.9 км",
    city: "Praha",
    description:
      "Українська кондитерська-ресторан у Виноградах: десерти, кава та сучасні страви.",
  },
  {
    id: "bon-makaronn",
    name: "Bon makaronn",
    category: "cafe",
    address: "Čestmírova 145/8, Praha",
    lat: 50.06420404127329,
    lng: 14.443053599337452,
    phone: "+420 720 327 172",
    website: "https://www.instagram.com/bon.makaronn/",
    hours: { today: "Уточнюється" },
    languages: ["uk", "cs"],
    tags: ["кондитерська", "макарони", "авторське"],
    photos: ["https://www.uagastromapa.cz/img/restaurants/bonmakaron.png"],
    is_verified: true,
    is_active: true,
    is_free: false,
    views_count: 528,
    saves_count: 116,
    rating: 4.8,
    review_count: 18,
    distance_label: "2.5 км",
    city: "Praha",
    description:
      "Авторська кондитерська з десертами на замовлення та камерним українським вайбом.",
  },
  {
    id: "biskvit-kavarna",
    name: "Biskvit",
    category: "cafe",
    address: "Ostrovského 2264/33, Praha",
    lat: 50.067690304815294,
    lng: 14.396732726270482,
    phone: "+420 774 211 401",
    website: "https://www.instagram.com/biskvit.kavarna",
    hours: { today: "Уточнюється" },
    languages: ["uk", "cs"],
    tags: ["кафе", "десерти", "сніданки"],
    photos: ["https://www.uagastromapa.cz/img/restaurants/biskvit.png"],
    is_verified: true,
    is_active: true,
    is_free: false,
    views_count: 684,
    saves_count: 155,
    rating: 4.7,
    review_count: 22,
    distance_label: "2.8 км",
    city: "Praha",
    description:
      "Кафе в районі Smíchov/Anděl з десертами, кавою та зручним місцем для зустрічі.",
  },
  {
    id: "the-borsch",
    name: "The Boršč",
    category: "cafe",
    address: "Dukelských hrdinů 10, Praha",
    lat: 50.099055589131765,
    lng: 14.433449506064383,
    phone: null,
    website: "https://theborsch.cz",
    hours: { today: "Уточнюється" },
    languages: ["uk", "cs", "en"],
    tags: ["ресторан", "борщ", "українська кухня"],
    photos: ["https://www.uagastromapa.cz/img/restaurants/borsc.png"],
    is_verified: true,
    is_active: true,
    is_free: false,
    views_count: 1054,
    saves_count: 286,
    rating: 4.8,
    review_count: 44,
    distance_label: "2.9 км",
    city: "Praha",
    description:
      "Ресторан сучасної української кухні біля Letná/Holešovice з акцентом на знайомі смаки.",
  },
  {
    id: "dnister",
    name: "Dnister",
    category: "cafe",
    address: "Na Moráni 1749/6, Praha 2",
    lat: 50.07339410073669,
    lng: 14.415953368655044,
    phone: "+420 739 020 889",
    website: "https://www.instagram.com/restaurace_dnister/",
    hours: { today: "Уточнюється" },
    languages: ["uk", "cs"],
    tags: ["ресторан", "традиційна кухня", "центр"],
    photos: ["https://www.uagastromapa.cz/img/restaurants/dnister.png"],
    is_verified: true,
    is_active: true,
    is_free: false,
    views_count: 1180,
    saves_count: 333,
    rating: 4.6,
    review_count: 57,
    distance_label: "1.2 км",
    city: "Praha",
    description:
      "Один із впізнаваних українських ресторанів у центрі Праги з традиційними стравами.",
  },
  {
    id: "gazda-jesenice",
    name: "GAZDA family hotel & restaurant",
    category: "cafe",
    address: "Budějovická 1500, Jesenice u Prahy",
    lat: 49.95325999647435,
    lng: 14.537202747590202,
    phone: "+420 778 087 757",
    website: "https://www.gazdafamily.cz",
    hours: { today: "Уточнюється" },
    languages: ["uk", "cs"],
    tags: ["ресторан", "готель", "сімейне"],
    photos: ["https://www.uagastromapa.cz/img/restaurants/gazda.png"],
    is_verified: true,
    is_active: true,
    is_free: false,
    views_count: 645,
    saves_count: 151,
    rating: 4.7,
    review_count: 21,
    distance_label: "14 км",
    city: "Jesenice",
    description:
      "Сімейний ресторан і готель біля Праги з українськими стравами та простором для подій.",
  },
  {
    id: "gazda-restaurant",
    name: "GAZDA restaurant",
    category: "cafe",
    address: "Přátelství 107/76, Praha",
    lat: 50.029744124412964,
    lng: 14.601920683983765,
    phone: "+420 778 088 757",
    website: "https://www.instagram.com/gazda_restaurant_/",
    hours: { today: "Уточнюється" },
    languages: ["uk", "cs"],
    tags: ["ресторан", "традиційна кухня", "родинне"],
    photos: ["https://www.uagastromapa.cz/img/restaurants/gazda1.png"],
    is_verified: true,
    is_active: true,
    is_free: false,
    views_count: 602,
    saves_count: 139,
    rating: 4.7,
    review_count: 20,
    distance_label: "12 км",
    city: "Praha",
    description:
      "Український ресторан на південному сході Праги, зручний для родинних вечерь і свят.",
  },
  {
    id: "bonjour-praha",
    name: "Bonjur",
    category: "cafe",
    address: "Mochovská 535/38, Praha",
    lat: 50.1070428967411,
    lng: 14.537332282093958,
    phone: "+420 776 625 105",
    website: "https://bonjour-bistro.cz",
    hours: { today: "Уточнюється" },
    languages: ["uk", "cs"],
    tags: ["bistro", "кава", "десерти"],
    photos: ["https://www.uagastromapa.cz/img/restaurants/bonjour.png"],
    is_verified: true,
    is_active: true,
    is_free: false,
    views_count: 471,
    saves_count: 98,
    rating: 4.6,
    review_count: 16,
    distance_label: "7.4 км",
    city: "Praha",
    description:
      "Бістро з українськими власниками, кавою, десертами та неформальною атмосферою району.",
  },
  {
    id: "burgery-bublinky",
    name: "Burgery & Bublinky",
    category: "cafe",
    address: "Hartigova 608/7, Praha 3",
    lat: 50.087594215142985,
    lng: 14.45418299743577,
    phone: null,
    website: "https://bu-bu.cz",
    hours: { today: "Уточнюється" },
    languages: ["uk", "cs"],
    tags: ["ресторан", "бургери", "жижков"],
    photos: [],
    is_verified: true,
    is_active: true,
    is_free: false,
    views_count: 552,
    saves_count: 122,
    rating: 4.5,
    review_count: 18,
    distance_label: "2.6 км",
    city: "Praha",
    description:
      "Ресторан у Žižkov із бургерами та casual-форматом для швидкої вечері або зустрічі.",
  },
  {
    id: "cream-and-dream",
    name: "Cream&Dream",
    category: "cafe",
    address: "Kodaňská 33, Praha 10",
    lat: 50.0714226,
    lng: 14.4554765,
    phone: "+420 775 914 394",
    website: "https://www.instagram.com/cream_and_dream_prague",
    hours: { today: "Уточнюється" },
    languages: ["uk", "cs"],
    tags: ["gelateria", "кондитерська", "десерти"],
    photos: [],
    is_verified: true,
    is_active: true,
    is_free: false,
    views_count: 508,
    saves_count: 118,
    rating: 4.7,
    review_count: 17,
    distance_label: "2.9 км",
    city: "Praha",
    description:
      "Десерти й морозиво у Vršovice, корисна точка для кави після прогулянки районом.",
  },
  {
    id: "maison-cafe",
    name: "Maison Cafe",
    category: "cafe",
    address: "Žitomírská 37, Praha 10",
    lat: 50.0715097,
    lng: 14.4580664,
    phone: "+420 775 914 394",
    website: "https://www.instagram.com/maison_cafe_prague",
    hours: { today: "Уточнюється" },
    languages: ["uk", "cs"],
    tags: ["кафе", "десерти", "vrsovice"],
    photos: [],
    is_verified: true,
    is_active: true,
    is_free: false,
    views_count: 533,
    saves_count: 127,
    rating: 4.7,
    review_count: 19,
    distance_label: "3.0 км",
    city: "Praha",
    description:
      "Кафе у Vršovice з десертами, кавою та дружнім форматом для сусідських зустрічей.",
  },
  {
    id: "restaurant-bellissimo",
    name: "Restaurant Bellissimo",
    category: "cafe",
    address: "Mělnická 582/13, Praha 5",
    lat: 50.0799157,
    lng: 14.405093,
    phone: "+420 732 577 657",
    website: "https://trattoria-bellissimo.com",
    hours: { today: "Уточнюється" },
    languages: ["uk", "cs", "en"],
    tags: ["ресторан", "події", "malá strana"],
    photos: [],
    is_verified: true,
    is_active: true,
    is_free: false,
    views_count: 495,
    saves_count: 104,
    rating: 4.5,
    review_count: 14,
    distance_label: "1.7 км",
    city: "Praha",
    description:
      "Ресторан біля Malá Strana, корисний для вечері, зустрічей і невеликих подій.",
  },
  {
    id: "atmosfera-praha",
    name: "Atmosfera",
    category: "cafe",
    address: "Veronské náměstí 403, Praha",
    lat: 50.0407974,
    lng: 14.5590684,
    phone: "+420 777 070 286",
    website: "https://www.atmosferacz.cz",
    hours: { today: "Уточнюється" },
    languages: ["uk", "cs"],
    tags: ["ресторан", "сімейне", "прага"],
    photos: [],
    is_verified: true,
    is_active: true,
    is_free: false,
    views_count: 437,
    saves_count: 94,
    rating: 4.5,
    review_count: 13,
    distance_label: "9.3 км",
    city: "Praha",
    description:
      "Ресторан у східній частині Праги для сімейних обідів, вечерь і локальних зустрічей.",
  },
  {
    id: "cernomorka",
    name: "Černomorka",
    category: "cafe",
    address: "Ondříčkova 1234/17, Praha 3",
    lat: 50.0819953,
    lng: 14.4558889,
    phone: "+420 722 360 505",
    website: "https://cernomorka.cz",
    hours: { today: "Уточнюється" },
    languages: ["uk", "cs"],
    tags: ["ресторан", "риба", "жижков"],
    photos: ["https://www.uagastromapa.cz/img/restaurants/cernomorka1.png"],
    is_verified: true,
    is_active: true,
    is_free: false,
    views_count: 778,
    saves_count: 203,
    rating: 4.8,
    review_count: 29,
    distance_label: "2.7 км",
    city: "Praha",
    description:
      "Ресторан у Žižkov із морською тематикою та українською підприємницькою історією.",
  },
  {
    id: "khromberry",
    name: "Khromberry",
    category: "cafe",
    address: "V Jirchářích 149/6, Praha 1",
    lat: 50.0798878,
    lng: 14.4161426,
    phone: "+420 724 274 573",
    website: "https://www.instagram.com/khromberry.cz",
    hours: { today: "Уточнюється" },
    languages: ["uk", "cs"],
    tags: ["кафе", "кондитерська", "торти"],
    photos: [],
    is_verified: true,
    is_active: true,
    is_free: false,
    views_count: 589,
    saves_count: 145,
    rating: 4.8,
    review_count: 23,
    distance_label: "0.8 км",
    city: "Praha",
    description:
      "Кафе-кондитерська в центрі Праги з тортами на замовлення, десертами та кавою.",
  },
  {
    id: "la-macarons",
    name: "La Macarons",
    category: "cafe",
    address: "Terronská 873/3, Praha",
    lat: 50.1016486,
    lng: 14.3992083,
    phone: null,
    website: "https://www.instagram.com/la_macaronss",
    hours: { today: "Уточнюється" },
    languages: ["uk", "cs"],
    tags: ["кафе", "макарони", "десерти"],
    photos: [],
    is_verified: true,
    is_active: true,
    is_free: false,
    views_count: 384,
    saves_count: 83,
    rating: 4.6,
    review_count: 11,
    distance_label: "4.1 км",
    city: "Praha",
    description:
      "Камерне кафе з авторськими десертами в Dejvice/Bubeneč, зручне для кави й подарунків.",
  },
  {
    id: "ukrainian-saturday-school",
    name: "Українська суботня школа",
    category: "community",
    address: "Vinohrady, Praha 2",
    lat: 50.072,
    lng: 14.4418,
    phone: null,
    website: null,
    hours: { today: "Сб 10:00-14:00" },
    languages: ["uk"],
    tags: ["діти", "культура", "зустрічі"],
    photos: [],
    is_verified: false,
    is_active: true,
    is_free: true,
    views_count: 512,
    saves_count: 174,
    rating: 4.7,
    review_count: 17,
    distance_label: "1.8 км",
    city: "Praha",
    description:
      "Мок-точка для майбутніх освітніх і культурних занять українською для дітей і батьків.",
  },
  {
    id: "ukrainian-meetups-hybernska",
    name: "Українські зустрічі в Kampus Hybernská",
    category: "community",
    address: "Hybernská 4, Praha 1",
    lat: 50.0872,
    lng: 14.4314,
    phone: null,
    website: "https://kampushybernska.cz",
    hours: { today: "Події за розкладом" },
    languages: ["uk", "cs", "en"],
    tags: ["події", "нетворкінг", "культура"],
    photos: [],
    is_verified: true,
    is_active: true,
    is_free: true,
    views_count: 577,
    saves_count: 165,
    rating: 4.8,
    review_count: 22,
    distance_label: "0.8 км",
    city: "Praha",
    description:
      "Міський культурний простір, де зручно проводити зустрічі, лекції та події української спільноти.",
  },
];
