import type { Place } from "@/lib/types";

export const MOCK_PLACES: Place[] = [
  {
    id: "ua-embassy",
    name: "Посольство України в Чехії",
    category: "legal",
    address: "Charlese de Gaulle 29, Praha 6",
    lat: 50.1038,
    lng: 14.3946,
    phone: "+420 233 342 000",
    website: "https://czechia.mfa.gov.ua",
    hours: { today: "09:00-12:00" },
    languages: ["uk", "cs"],
    tags: ["документи", "консульство", "офіційно"],
    photos: [],
    is_verified: true,
    is_active: true,
    is_free: true,
    views_count: 1254,
    saves_count: 318,
    rating: 4.8,
    review_count: 40,
    distance_label: "4.2 км",
    description: "Консульські послуги, оформлення документів і базова навігація з офіційних питань.",
  },
  {
    id: "cic-praha",
    name: "Centrum pro integraci cizinců",
    category: "legal",
    address: "Jeremenkova 5, Praha 4",
    lat: 50.0479,
    lng: 14.4246,
    phone: "+420 296 325 345",
    website: "https://cicpraha.org",
    hours: { today: "10:00-17:00" },
    languages: ["uk", "cs", "en"],
    tags: ["інтеграція", "право", "безкоштовно"],
    photos: [],
    is_verified: true,
    is_active: true,
    is_free: true,
    views_count: 943,
    saves_count: 221,
    rating: 4.7,
    review_count: 28,
    distance_label: "3.8 км",
    description: "Безкоштовна юридична та соціальна допомога для іноземців у Празі.",
  },
  {
    id: "nova-skola",
    name: "Nová škola: курси чеської",
    category: "language",
    address: "Ostrovského 253, Praha 5",
    lat: 50.0692,
    lng: 14.4021,
    phone: "+420 257 942 320",
    website: "https://novaskola.org",
    hours: { today: "08:30-18:00" },
    languages: ["uk", "cs"],
    tags: ["чеська", "курси", "сертифікат"],
    photos: [],
    is_verified: true,
    is_active: true,
    is_free: false,
    views_count: 732,
    saves_count: 147,
    rating: 4.9,
    review_count: 19,
    distance_label: "2.1 км",
    description: "Курси чеської мови для дорослих та підлітків, групи A1-B2.",
  },
  {
    id: "pediatrician-vinohrady",
    name: "Педіатрія Виногради",
    category: "medicine",
    address: "Vinohrady, Praha 2",
    lat: 50.075,
    lng: 14.448,
    phone: "+420 777 123 456",
    website: null,
    hours: { today: "12:00-16:30" },
    languages: ["uk", "cs"],
    tags: ["діти", "українською", "прийом"],
    photos: [],
    is_verified: true,
    is_active: true,
    is_free: false,
    views_count: 1189,
    saves_count: 396,
    rating: 4.6,
    review_count: 52,
    distance_label: "1.6 км",
    description: "Україномовний прийом дітей, профілактичні огляди та консультації для родин.",
  },
  {
    id: "crisis-support",
    name: "Психологічна підтримка CKI",
    category: "medicine",
    address: "Ústavní 91, Praha 8",
    lat: 50.1186,
    lng: 14.4638,
    phone: "+420 284 016 666",
    website: null,
    hours: { today: "24/7" },
    languages: ["uk", "cs", "en"],
    tags: ["психолог", "криза", "безкоштовно"],
    photos: [],
    is_verified: true,
    is_active: true,
    is_free: true,
    views_count: 814,
    saves_count: 265,
    rating: 4.8,
    review_count: 33,
    distance_label: "6.7 км",
    description: "Кризова психологічна допомога і маршрутизація до профільних служб.",
  },
  {
    id: "jobs-for-ukraine",
    name: "Jobs for Ukraine Praha",
    category: "work",
    address: "Václavské náměstí 1, Praha 1",
    lat: 50.081,
    lng: 14.4277,
    phone: null,
    website: "https://jobsforukraine.net",
    hours: { today: "Онлайн" },
    languages: ["uk", "cs", "en"],
    tags: ["робота", "вакансії", "консультації"],
    photos: [],
    is_verified: true,
    is_active: true,
    is_free: true,
    views_count: 856,
    saves_count: 202,
    rating: 4.5,
    review_count: 25,
    distance_label: "0.7 км",
    description: "Підбір вакансій, ярмарки роботи та консультації щодо працевлаштування.",
  },
  {
    id: "ukrainian-housing-help",
    name: "Житлова консультація Praha",
    category: "housing",
    address: "Karlovo náměstí 7, Praha 2",
    lat: 50.0753,
    lng: 14.4188,
    phone: "+420 602 410 900",
    website: null,
    hours: { today: "11:00-17:00" },
    languages: ["uk", "cs"],
    tags: ["оренда", "договір", "райони"],
    photos: [],
    is_verified: false,
    is_active: true,
    is_free: true,
    views_count: 488,
    saves_count: 109,
    rating: 4.4,
    review_count: 12,
    distance_label: "1.1 км",
    description: "Пояснення договорів оренди, депозитів, районів Праги та базових правил житла.",
  },
  {
    id: "ridne-shop",
    name: "Крамниця Рідне",
    category: "shops",
    address: "Žižkov, Praha 3",
    lat: 50.0853,
    lng: 14.4521,
    phone: "+420 608 987 654",
    website: null,
    hours: { today: "09:00-20:00" },
    languages: ["uk"],
    tags: ["продукти", "книги", "з України"],
    photos: [],
    is_verified: true,
    is_active: true,
    is_free: false,
    views_count: 641,
    saves_count: 113,
    rating: 4.7,
    review_count: 18,
    distance_label: "2.4 км",
    description: "Українські продукти, косметика, книжки та дрібні речі для дому.",
  },
  {
    id: "ua-service-shop",
    name: "UA Service Point",
    category: "shops",
    address: "Anděl, Praha 5",
    lat: 50.0714,
    lng: 14.403,
    phone: "+420 775 330 112",
    website: null,
    hours: { today: "10:00-19:00" },
    languages: ["uk", "cs"],
    tags: ["послуги", "перекази", "друк"],
    photos: [],
    is_verified: false,
    is_active: true,
    is_free: false,
    views_count: 302,
    saves_count: 51,
    rating: 4.3,
    review_count: 9,
    distance_label: "2.2 км",
    description: "Друк документів, переклади контактів, побутові послуги та допомога з формами.",
  },
  {
    id: "lviv-croissants",
    name: "Lviv Croissants Praha",
    category: "cafe",
    address: "Senovážné náměstí 3, Praha 1",
    lat: 50.085,
    lng: 14.432,
    phone: null,
    website: null,
    hours: { today: "08:00-21:00" },
    languages: ["uk", "cs"],
    tags: ["кава", "перекус", "центр"],
    photos: [],
    is_verified: false,
    is_active: true,
    is_free: false,
    views_count: 421,
    saves_count: 88,
    rating: 4.5,
    review_count: 14,
    distance_label: "0.9 км",
    description: "Знайома їжа, кава і швидкі зустрічі поруч із центром Праги.",
  },
  {
    id: "ua-school",
    name: "Українська недільна школа",
    category: "community",
    address: "Vinohrady, Praha 2",
    lat: 50.072,
    lng: 14.4418,
    phone: null,
    website: null,
    hours: { today: "Сб 10:00-14:00" },
    languages: ["uk"],
    tags: ["діти", "культура", "зустрічі"],
    photos: [],
    is_verified: true,
    is_active: true,
    is_free: true,
    views_count: 512,
    saves_count: 174,
    rating: 4.9,
    review_count: 31,
    distance_label: "1.3 км",
    description: "Українська мова, культура та спільні заняття для дітей і батьків.",
  },
  {
    id: "ua-meetups",
    name: "Українські зустрічі в Kampus Hybernská",
    category: "community",
    address: "Hybernská 4, Praha 1",
    lat: 50.0872,
    lng: 14.4314,
    phone: null,
    website: "https://kampushybernska.cz",
    hours: { today: "Події за розкладом" },
    languages: ["uk", "cs", "en"],
    tags: ["події", "нетворкінг", "культура"],
    photos: [],
    is_verified: true,
    is_active: true,
    is_free: true,
    views_count: 577,
    saves_count: 165,
    rating: 4.8,
    review_count: 22,
    distance_label: "0.8 км",
    description: "Лекції, волонтерські зустрічі, культурні події та знайомства у центрі Праги.",
  },
];
